apiVersion: apps/v1
kind: Deployment
metadata:
  name: icecast
  labels:
    app: icecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icecast
  template:
    metadata:
      labels:
        app: icecast
    spec:
      containers:
        - name: icecast
          image: some/registry/container:tag
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: icecast
  labels:
    app: icecast
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: icecast
